### ISSUE TITLE
[idea] Github robot

### ISSUE THREAD

**Issue by gaocegege** [dyweb/mos#1]
\cc @dyweb/mos

idea issuer: @at15 & @gaocegege & @arrowrowe 

ref https://github.com/dyweb/web-stuff/issues/113#issuecomment-256715463

> @gaocegege I think we can use a issue comment template like the following. (Attach the template to the issue so every one can copy and paste it since gh does not have issue comment template)
> 
> ```
> - tags: php, best-lang
> - keywords: hybrid
> - link: https://github.com/deuill/go-php
> - comment: Use PHP with go
> - cc: @ComMouse
> ```
> 
> (or maybe just use the yaml format) so the bot would be easier to implement 
> 
> Also using a machine understandable language make it easier to do search and build an interactive gh-page for weekly, for search https://www.algolia.com/ seems to be a good solution.

外国友人 @at15 的 idea

目测要求：

1. 了解 HTTP/HTTPS 请求
2. 有一门顺手的比较快糙猛的语言(python, ruby, golang, js, ...)
3. 可以阅读英文文档

**Comment by gaocegege** [comment]
进阶需求：

实现一个诸如 [michael/github](https://github.com/michael/github) 的 API 抽象，便于之后为 bot 加 feature

**Comment by gaocegege** [comment]
可用的 library：

1. https://github.com/PyGithub/PyGithub

**Comment by gaocegege** [comment]
这个 idea 可以分为两个部分

一部分是建立一个类似 hook 的机制，能够捕捉到 @ bot 的comment，然后拿到相应的 issue

另外一个部分是拿到 issue 所有的按照 https://github.com/dyweb/mos/issues/1#issue-186110914 的格式的 comment，把他们全部合并成一个 markdown，作为周报提交一个 PR

目标 repo 是 https://github.com/dyweb/weekly

**Comment by arrowrowe** [comment]
需要定义好 comment 格式和合并方式什么的

**Comment by gaocegege** [comment]
嗯不过我觉得比较麻烦是前面一个，没有一个针对 issue 中的 mention 的webhook

**Comment by ComMouse** [comment]
给 repo 加个 issue create 的 webhook 就可以了吧

**Comment by arrowrowe** [comment]
@ComMouse 诶? create 下一期周报 issue 时自动找上一期么?... 倒是也挺机智的 = =

**Comment by gaocegege** [comment]
忽然想到，不需要，可以按照时间来判断

捂脸

**Comment by arrowrowe** [comment]
......挺好... 每周三 23:59:59 启动, lock, push, close, open......

**Comment by arrowrowe** [comment]
关于 comment 格式,

- YAML ([The Official YAML Web Site](http://yaml.org/), 库可以用 [ruamel.yaml](https://pypi.python.org/pypi/ruamel.yaml)).

**Comment by arrowrowe** [comment]
关于 comment 具体规范,

属性: name, link, description, quote, comment, cc. 除 name 外都可选.
- 如果有 link, 为 name 加上
- 如果有 description, 在 name 后加 `, ` 接上
- 如果有 quote, 以引用格式附上
- 如果有 comment, 标上投稿者附上
- 如果有 cc (可以是单个用户, 直接逗号分开, 或者写成 list), 挨个 @

属性完整的例子: (写的时候... 不熟悉的话还是在 [Online YAML Parser](http://yaml-online-parser.appspot.com/) 里写的好......)
```yaml
name: mhagger/git-when-merged
link: https://github.com/mhagger/git-when-merged
description: >
    the `git when-merged` utility.
quote: >
    `git when-merged` helps you figure out when and why a commit
    was merged into a branch.
comment: >
    适用于 "为什么我 merge 了一下 master 编译就跪了 / 原来是这个
    commit 的锅, 它怎么进 master 的"
cc: gaocegege
```

Format 为:
- [mhagger/git-when-merged](https://github.com/mhagger/git-when-merged), the `git when-merged` utility.

    > `git when-merged` helps you figure out when and why a commit was merged into a branch.

    ___@arrowrowe:___ 适用于 "为什么我 merge 了一下 master 编译就跪了 / 原来是这个 commit 的锅, 它怎么进 master 的"

    cc @gaocegege
